version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tripdai
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tripdai
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
